ex1:
	g++ excercise1.cpp -o e1.out
run-ex1:
	./e1.out $(ARG) 
ex2:
	g++ excercise2.cpp -o e2.out
run-ex2:
	./e2.out $(ARG)
ex3:
	g++ excercise3.cpp -o e3.out
run-ex3:
	./e3.out
ex4:
	g++ excercise4.cpp -o e4.out
run-ex4:
	./e4.out
ex5:
	g++ excercise5.cpp -o e5.out
run-ex5:
	./e5.out
ex6:
	g++ excercise6.cpp -o e6.out
run-ex6:
	./e6.out
